### ISSUE TITLE
Erors DB

### ISSUE THREAD

**Issue by smithy9901** [Nutty101/NPC-Police#12] opened 2018-04-16 11:57 UTC
Database mariadb, the user has all rights to the database.

[14:32:08] [NPC_Police-MySql DB/WARN]: Exception in thread "NPC_Police-MySql DB" 
[14:32:08] [NPC_Police-MySql DB/WARN]: java.lang.NullPointerException
[14:32:08] [NPC_Police-MySql DB/WARN]:     at net.livecar.nuttyworks.npc_police.database.Database_MySql.getUserData(Database_MySql.java:381)
[14:32:08] [NPC_Police-MySql DB/WARN]:     at net.livecar.nuttyworks.npc_police.database.Database_MySql.processQueue(Database_MySql.java:270)
[14:32:08] [NPC_Police-MySql DB/WARN]:     at net.livecar.nuttyworks.npc_police.database.Database_MySql.run(Database_MySql.java:218)
[14:32:08] [NPC_Police-MySql DB/WARN]:     at java.lang.Thread.run(Thread.java:748)

**Comment by smithy9901** [comment] 2018-04-16 12:11
![default](https://user-images.githubusercontent.com/37003941/38808337-72e4adce-4188-11e8-94ed-2e52d4c63f82.jpg)

**Comment by smithy9901** [comment] 2018-04-16 12:36
Server after 15-30 minutes of working with your plugin crash

**Comment by Nutty101** [comment] 2018-04-17 02:53
Could you post the last part of the log, or PM me on spigot with it? Curious what would be the cause of it. I will fire up a server mariadb as well to see if I can find anything.

**Comment by smithy9901** [comment] 2018-04-17 12:30
I could give you access to the logs and consol, they are in my discord

[2018-04-12-2.log](https://github.com/Nutty101/NPC-Police/files/1919638/2018-04-12-2.log)

**Comment by smithy9901** [comment] 2018-04-18 11:43
Write here to agree on time.
https://discord.gg/HGjYAzN

**Comment by Nutty101** [comment] 2018-12-03 00:11
Version 2.2.1 should address this. Closing for now, reopen if it's still an issue.

**Closed by Nutty101** 2018-12-03 00:11 UTC
Labels: bug
